### ISSUE TITLE
Create a moon shape

### ISSUE THREAD

**Issue by alitonia** [leehoang2000/WeebSpace#7]
# Feature request

### Description:

Create a simple moon to test logic.

### Why this feature?

Moon is an essential component to gameplay

### How to implement:

No idea. Please check the doc for more information.

**Comment by alitonia** [comment]
@I'm working on it

**Comment by DrakeGoCoding** [comment]
@i'm working on it

**Comment by middle-way-approach** [comment]
For others to help a little bit of context would be nice. For example the filetype, size and other architectural decision like where are the assets stored etc.

**Comment by alitonia** [comment]
Great idea. I shall update the docs for that.

In the mean time, I could tell you that:

* We are using [Godot](https://godotengine.org/) for developing this game, using __GDScript__.
* As we are currently short of time ( deadline is 1st Dec), we decided to let developers implement to their own, as long as it it functional 😅
* For filetype, go with what __Godot__ gives you. 
* For size, do it how you see fit, but the simpler the better.
* For assets, i will make a folder for that. 


Thank you for your proposal 🥰.
